image: registry.gitlab.com/facteus/platform-team/shared-infra/images/dotnet-ci-image:latest

stages:
  - pre-deploy
  - build
  - deploy-develop
  - deploy-staging
  - deploy-production

variables:
  AWS_ACCESS_KEY_ID: $QMC_DEPLOY_USER_ACCESS_KEY_ID_DEV
  AWS_SECRET_ACCESS_KEY: $QMC_DEPLOY_USER_SECRET_ACCESS_KEY_DEV
  AWS_DEFAULT_REGION: us-west-2
  ENV_SUFFIX: development
  STACK_NAME: qmc-web-ui-$ENV_SUFFIX
  TEMPLATE_PATH: website.yml
  CERTIFICATE_ARN: arn:aws:acm:us-east-1:383101536740:certificate/29d974c2-caef-44cf-bd78-4e6102652152
  DISTRIBUTION_ALIAS: dev.quantamatics.net

validate template:
  stage: pre-deploy
  script:
  - aws cloudformation validate-template --template-body file://$TEMPLATE_PATH

build:
  image: node:lts
  dependencies:
    - validate template
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build && mv publish dist-development
    - npm run buildBeta && mv publish dist-development-beta
    - npm run buildStaging && mv publish dist-staging
    - npm run buildStagingBeta && mv publish dist-staging-beta
  artifacts:
    paths:
      - dist-development/
      - dist-development-beta/
      - dist-staging/
      - dist-staging-beta/
      
.deploy:
  dependencies:
    - build
  script:
    - aws cloudformation deploy --stack-name $STACK_NAME --template-file $TEMPLATE_PATH --no-fail-on-empty-changeset --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND --parameter-overrides "CertificateArn=$CERTIFICATE_ARN" "DistributionAlias=$DISTRIBUTION_ALIAS"
    - aws s3 sync ./dist-$ENV_SUFFIX s3://$STACK_NAME --acl public-read
    - export DISTRIBUTION_ID=`aws cloudformation describe-stack-resource --stack-name $STACK_NAME --logical-resource-id CloudFrontDistribution | jq -r '.StackResourceDetail.PhysicalResourceId'`
    - invalidation_id=$(aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*" | jq -r '.Invalidation.Id')
    - echo $invalidation_id
    - aws cloudfront wait invalidation-completed --distribution-id $DISTRIBUTION_ID --id $invalidation_id

deploy dev:
  stage: deploy-develop
  extends: .deploy
  only:
    - develop

deploy dev beta:
  stage: deploy-develop
  extends: .deploy
  variables:
    ENV_SUFFIX: development-beta
    STACK_NAME: qmc-web-ui-$ENV_SUFFIX
    DISTRIBUTION_ALIAS: beta.dev.quantamatics.net
  only:
    - develop

deploy staging:
  stage: deploy-staging
  extends: .deploy
  variables:
    AWS_ACCESS_KEY_ID: $QMC_DEPLOY_USER_ACCESS_KEY_ID_STAG
    AWS_SECRET_ACCESS_KEY: $QMC_DEPLOY_USER_SECRET_ACCESS_KEY_STAG
    AWS_DEFAULT_REGION: us-east-1
    ENV_SUFFIX: staging
    STACK_NAME: qmc-web-ui-$ENV_SUFFIX
    CERTIFICATE_ARN: arn:aws:acm:us-east-1:873219636944:certificate/007c88f5-b68a-4a25-9ef6-fdf8c7100526
    DISTRIBUTION_ALIAS: stag.quantamatics.net    
  only:
    - master

deploy staging beta:
  stage: deploy-staging
  extends: .deploy
  variables:
    AWS_ACCESS_KEY_ID: $QMC_DEPLOY_USER_ACCESS_KEY_ID_STAG
    AWS_SECRET_ACCESS_KEY: $QMC_DEPLOY_USER_SECRET_ACCESS_KEY_STAG
    AWS_DEFAULT_REGION: us-east-1
    ENV_SUFFIX: staging-beta
    STACK_NAME: qmc-web-ui-$ENV_SUFFIX
    CERTIFICATE_ARN: arn:aws:acm:us-east-1:873219636944:certificate/007c88f5-b68a-4a25-9ef6-fdf8c7100526
    DISTRIBUTION_ALIAS: beta.stag.quantamatics.net    
  only:
    - master