// Generated by https://quicktype.io

export interface EChartTheme {
	color:           string[];
	backgroundColor: string;
	textStyle:       TextStyle;
	title:           Title;
	line:            Line;
	radar:           Line;
	bar:             Bar;
	pie:             Boxplot;
	scatter:         Boxplot;
	boxplot:         Boxplot;
	parallel:        Boxplot;
	sankey:          Boxplot;
	funnel:          Boxplot;
	gauge:           Boxplot;
	candlestick:     Candlestick;
	graph:           Graph;
	map:             Geo;
	geo:             Geo;
	categoryAxis:    Axis;
	valueAxis:       Axis;
	logAxis:         Axis;
	timeAxis:        Axis;
	toolbox:         Toolbox;
	legend:          Legend;
	tooltip:         Tooltip;
	timeline:        Timeline;
	visualMap:       VisualMap;
	dataZoom:        DataZoom;
	markPoint:       MarkPoint;
}

export interface Bar {
	itemStyle: BarItemStyle;
}

export interface BarItemStyle {
	barBorderWidth: number;
	barBorderColor: string;
}

export interface Boxplot {
	itemStyle: BoxplotItemStyle;
}

export interface BoxplotItemStyle {
	borderWidth: number;
	borderColor: string;
}

export interface Candlestick {
	itemStyle: CandlestickItemStyle;
}

export interface CandlestickItemStyle {
	color:        string;
	color0:       string;
	borderColor:  string;
	borderColor0: string;
	borderWidth:  number;
}

export interface Axis {
	axisLine:  AxisLineClass;
	axisTick:  AxisLineClass;
	axisLabel: AxisLabel;
	splitLine: SplitLine;
	splitArea: SplitArea;
}

export interface AxisLabel {
	show:  boolean;
	color: string;
}

export interface AxisLineClass {
	show:      boolean;
	lineStyle: Label;
}

export interface Label {
	color: string;
}

export interface SplitArea {
	show:      boolean;
	areaStyle: VisualMap;
}

export interface VisualMap {
	color: string[];
}

export interface SplitLine {
	show:      boolean;
	lineStyle: VisualMap;
}

export interface DataZoom {
	handleSize: string;
	textStyle:  TextStyle;
}

export interface TextStyle {
}

export interface Geo {
	itemStyle: EmphasisItemStyle;
	label:     Label;
	emphasis:  GeoEmphasis;
}

export interface GeoEmphasis {
	itemStyle: EmphasisItemStyle;
	label:     Label;
}

export interface EmphasisItemStyle {
	areaColor:   string;
	borderColor: string;
	borderWidth: number;
}

export interface Graph {
	itemStyle:  BoxplotItemStyle;
	lineStyle:  Style;
	symbolSize: number;
	symbol:     string;
	smooth:     boolean;
	color:      string[];
	label:      Label;
}

export interface Style {
	width: number;
	color: string;
}

export interface Legend {
	textStyle: Label;
}

export interface Line {
	itemStyle:  LineItemStyle;
	lineStyle:  LineStyle;
	symbolSize: number;
	symbol:     string;
	smooth:     boolean;
}

export interface LineItemStyle {
	borderWidth: number;
}

export interface LineStyle {
	width: number;
}

export interface MarkPoint {
	label:    Label;
	emphasis: MarkPointEmphasis;
}

export interface MarkPointEmphasis {
	label: Label;
}

export interface Timeline {
	lineStyle:       Style;
	itemStyle:       TimelineItemStyle;
	controlStyle:    ControlStyle;
	checkpointStyle: CheckpointStyle;
	label:           Label;
	emphasis:        TimelineEmphasis;
}

export interface CheckpointStyle {
	color:       string;
	borderColor: string;
}

export interface ControlStyle {
	color:       string;
	borderColor: string;
	borderWidth: number;
}

export interface TimelineEmphasis {
	itemStyle:    Label;
	controlStyle: ControlStyle;
	label:        Label;
}

export interface TimelineItemStyle {
	color:       string;
	borderWidth: number;
}

export interface Title {
	textStyle:    Label;
	subtextStyle: Label;
}

export interface Toolbox {
	iconStyle: IconStyle;
	emphasis:  ToolboxEmphasis;
}

export interface ToolboxEmphasis {
	iconStyle: IconStyle;
}

export interface IconStyle {
	borderColor: string;
}

export interface Tooltip {
	axisPointer: AxisPointer;
}

export interface AxisPointer {
	lineStyle:  Style;
	crossStyle: Style;
}
